services:
  tedge:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    tmpfs:
      - /tmp
    volumes:
      - device_certs:/etc/tedge/device-certs

volumes:
  device_certs:
    external:
      name: device-certs
